### ISSUE TITLE
Extending doNonlinearEffectsAnalysis()

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#405]
To do:

- [ ] For the surface analysis it might be benefical to have a postestiate function that calculate the intercepts, e.g., b12*rho12. (previously #390)
- [x] Implement higher-order terms including the calculation of JN point for floodlight analysis. (previously #404)
- [x] First-order derivations need to be implemented... (previously #404)
- [x] Update print for `doNonlinearEffectsAnalysis()` to include JN points (once @FloSchuberth has decided how JN points are returned by the function)
- [x] Add examples illustrating:
    - [x] Floodlight analysis
    - [x] Surface analysis
    - [x] Simple effects analysis 

### To do @FloSchuberth 
- [x] Add arguments `.path_coefficients`, `.steps_mod`, and `.level_iv` to `zz_arguments.R`
- [x] Rewrite description of argument `.values_independent` (I dont understand the description);
      Consider adding a case to the examples that illustrates how these arguments are used.
- [x] `plot(neffects, .plot_type = 'surface', .plot_package = 'plotly')` from the examples section doesnt return anything. Please check

**Comment by FloSchuberth** [comment]
Implementation of the JN is done , see Issue_406, the output is a matrix. So the print method can updated.
In doing so, the level of the independent variable should be reported. It is stored under Information
Flood for nonlinear terms is implemented including fundtion that calculates first derivative, see Issue_406.
Where do I have to impement the examples?

**Comment by M-E-Rademaker** [comment]
- Could you please checkmark which of the to dos above is done; I dont know if some of them are still open or not.
- Is issue_406 also implemented? If so please add it to the list of to dos and, if implemented, checkmark it and close issue 406.
- Add a file `example_doNonlinearEffectsAnalysis.R` to `inst/examples` and write an example illustrationg the most important features; reference the example file in the the roxygen code of the doNonlinearEffectsAnalysis function using `@example inst/examples/example_doNonlinearEffectsAnalysis.R`

**Comment by FloSchuberth** [comment]
I have chekced which issue are addressed. 

Issue 406 is not yet implemented but this is only a minor thing and will affect the output. 

The examples were already there and also connected to the doNonlinearEffects function.

**Comment by M-E-Rademaker** [comment]
Good, I will update the print then!

**Comment by FloSchuberth** [comment]
Dankö ☺

**Comment by M-E-Rademaker** [comment]
Added JN points to print. Remaining questions @FloSchuberth 

1. Can `.$Information$value_independent` be a vector of more than 1 value?
2. Can `.$out_floodlight$Johnson_Neyman_points` have more than 1 row; can it have more than two columns?
3. If either 1 or 2 is true. Does `.$Information$value_independent` always have the same number of elements as `.$out_floodlight$Johnson_Neyman_points` has rows?
4. What about the column names of `.$out_floodlight$Johnson_Neyman_points` (currently, `x` and `y`). Should they ne renamed. If so: how?

**Comment by M-E-Rademaker** [comment]
... and please, in the future, try to reduce the number of commits! It would make reviewing changes a lot easier....

**Comment by FloSchuberth** [comment]
Siehe meine Antworten unten

**Comment by M-E-Rademaker** [comment]
ok integrated; Btw: Travis is failing because the new lavaan version 0.6.6 has a bug. This used to work in versions prior to 0.6.6

```
require(cSEM) # for the threecommonfactors data set
require(lavaan)

model <- "
# Structural model
eta2 ~ eta1
eta3 ~ eta1 + eta2

# (Reflective) measurement model
eta1 =~ y11 + y12 + y13
eta2 =~ y21 + y22 + y23
eta3 =~ y31 + y32 + y33
"

aa <- sem(model, threecommonfactors)
lavPredict(aa, fsm = TRUE, method = "Bartlett")

## Fehler in lav_predict_eta_bartlett(lavobject = lavobject, lavmodel = lavmodel,  : 
##  Objekt 'FSM.g' nicht gefunden
```

I already notified Yves.

**Comment by M-E-Rademaker** [comment]
closed by #407
